extends RefCounted

# 四阶固定谱系：3个根源、3个二阶、11个三阶、55个四阶。
# 每个无序输入对至多对应一个结果；RECIPES按阶层顺序排列，便于测试完整可达性。
const ITEMS := {
	"water": {"name": "水", "tier": 1, "category": "根源", "description": "流动、冷却、滋养与侵蚀的起点。", "art_source": "material", "art_index": 0},
	"fire": {"name": "火", "tier": 1, "category": "根源", "description": "加热、转化、烧制与释放力量的起点。", "art_source": "material", "art_index": 2},
	"earth": {"name": "土", "tier": 1, "category": "根源", "description": "承载、混合、堆积与孕育的起点。", "art_source": "material", "art_index": 1},

	"steam": {"name": "蒸汽", "tier": 2, "category": "天象", "description": "水受热后获得上升与膨胀的形态。", "art_source": "creation", "art_index": 2},
	"mud": {"name": "泥", "tier": 2, "category": "材料", "description": "水进入土后形成可流动、可塑形的介质。", "art_source": "creation", "art_index": 0},
	"lava": {"name": "熔岩", "tier": 2, "category": "地质", "description": "土石受极热后形成的高温流体。", "art_source": "creation", "art_index": 1},

	"cloud": {"name": "云", "tier": 3, "category": "天象", "description": "蒸汽聚集并重新携带水分。", "art_source": "material", "art_index": 4},
	"swamp": {"name": "沼泽", "tier": 3, "category": "生境", "description": "水分长期停留在泥地形成的湿润环境。", "art_source": "material", "art_index": 12},
	"obsidian": {"name": "黑曜石", "tier": 3, "category": "地质", "description": "熔岩被水快速冷却形成的锋利火山玻璃。", "art_source": "material", "art_index": 5},
	"energy": {"name": "动力", "tier": 3, "category": "原理", "description": "蒸汽在持续热量中表现出的压力与做功能力。", "art_source": "material", "art_index": 9},
	"pottery": {"name": "陶器", "tier": 3, "category": "工艺", "description": "泥经火烧获得固定而耐久的形状。", "art_source": "creation", "art_index": 3},
	"eruption": {"name": "喷发", "tier": 3, "category": "地貌", "description": "熔岩在持续热力中突破束缚并向外释放。", "art_source": "creation", "art_index": 1},
	"geyser": {"name": "间歇泉", "tier": 3, "category": "地貌", "description": "地下水汽沿土层裂隙积压后周期喷出。", "art_source": "material", "art_index": 0},
	"clay": {"name": "黏土", "tier": 3, "category": "材料", "description": "细土与泥沉降结合，形成更均匀的塑形材料。", "art_source": "creation", "art_index": 0},
	"mountain": {"name": "山岳", "tier": 3, "category": "地貌", "description": "熔岩与大地长期堆积、凝固并抬升形成高地。", "art_source": "material", "art_index": 5},
	"mud_spring": {"name": "泥泉", "tier": 3, "category": "生境", "description": "蒸汽穿过泥层，把矿物与湿泥不断带到地表。", "art_source": "creation", "art_index": 0},
	"volcanic_cloud": {"name": "火山云", "tier": 3, "category": "天象", "description": "蒸汽与熔岩相遇后托起灰尘和高温气体。", "art_source": "creation", "art_index": 2},

	"rain": {"name": "雨", "tier": 4, "category": "天象", "description": "云在山岳抬升与降温中释放水分。", "art_source": "material", "art_index": 0},
	"thunderstorm": {"name": "雷暴", "tier": 4, "category": "天象", "description": "云层中的动力累积为强烈对流和雷电。", "art_source": "material", "art_index": 2},
	"fog": {"name": "雾", "tier": 4, "category": "天象", "description": "蒸汽混入低云，在近地面悬浮成细小水滴。", "art_source": "creation", "art_index": 2},
	"pyrocumulus": {"name": "火积云", "tier": 4, "category": "天象", "description": "喷发产生的强烈上升气流把云顶推得更高。", "art_source": "material", "art_index": 4},
	"volcanic_lightning": {"name": "火山闪电", "tier": 4, "category": "天象", "description": "火山云中的颗粒在剧烈运动中分离电荷并放电。", "art_source": "material", "art_index": 9},
	"ash_rain": {"name": "灰雨", "tier": 4, "category": "天象", "description": "水分裹住火山云中的灰尘，形成沉重的暗色降水。", "art_source": "creation", "art_index": 1},
	"dust_storm": {"name": "尘暴", "tier": 4, "category": "天象", "description": "干燥土尘进入云下气流，形成遮蔽天空的沙尘墙。", "art_source": "material", "art_index": 1},
	"smog": {"name": "烟霾", "tier": 4, "category": "天象", "description": "蒸汽托住细灰，使浑浊气团久久不能沉降。", "art_source": "creation", "art_index": 2},
	"plasma": {"name": "炽流", "tier": 4, "category": "原理", "description": "火继续向动力注入热量，使物质进入明亮的高能状态。", "art_source": "material", "art_index": 2},
	"rainforest": {"name": "雨林", "tier": 4, "category": "生境", "description": "云层持续补水，让沼泽边缘形成高湿度的繁盛生境。", "art_source": "material", "art_index": 3},

	"river": {"name": "河流", "tier": 4, "category": "地貌", "description": "水沿山势持续汇集并侵蚀出稳定通路。", "art_source": "material", "art_index": 0},
	"lake": {"name": "湖泊", "tier": 4, "category": "地貌", "description": "更多水进入低洼沼泽，形成开阔而稳定的水体。", "art_source": "material", "art_index": 0},
	"hot_spring": {"name": "温泉", "tier": 4, "category": "生境", "description": "间歇泉得到持续水源后，形成可长期蓄积的热水池。", "art_source": "material", "art_index": 0},
	"lahar": {"name": "火山泥流", "tier": 4, "category": "地貌", "description": "水卷走喷发物和松散灰土，沿坡面形成高速泥流。", "art_source": "creation", "art_index": 0},
	"volcano": {"name": "火山", "tier": 4, "category": "地貌", "description": "反复喷发在山岳上留下稳定的火山锥与通道。", "art_source": "creation", "art_index": 1},
	"crater": {"name": "火山口", "tier": 4, "category": "地貌", "description": "喷发冲破大地，在地表留下环形凹地。", "art_source": "material", "art_index": 5},
	"geothermal_field": {"name": "地热原", "tier": 4, "category": "地质", "description": "山体裂隙汇聚间歇泉与地下热量，形成成片热区。", "art_source": "material", "art_index": 5},
	"new_land": {"name": "熔岩新岸", "tier": 4, "category": "地貌", "description": "熔岩进入湿地后快速冷却并向水边延伸出新陆地。", "art_source": "material", "art_index": 5},
	"terrace": {"name": "梯田", "tier": 4, "category": "地貌", "description": "泥被分层留在山坡上，形成能够蓄水的连续台面。", "art_source": "material", "art_index": 1},
	"dam": {"name": "土坝", "tier": 4, "category": "工程", "description": "黏土封住山谷缺口，形成能够阻水的致密堤体。", "art_source": "creation", "art_index": 4},
	"mud_valley": {"name": "泥泉谷", "tier": 4, "category": "地貌", "description": "山势约束泥泉流向，长期切出富含矿泥的谷地。", "art_source": "creation", "art_index": 0},
	"plateau": {"name": "高原", "tier": 4, "category": "地貌", "description": "大地继续托举山岳，使大片高处趋于平缓稳定。", "art_source": "material", "art_index": 5},
	"volcanic_range": {"name": "火山群", "tier": 4, "category": "地貌", "description": "熔岩沿山体裂隙反复上涌，形成连续火山带。", "art_source": "creation", "art_index": 1},
	"mudflat": {"name": "泥滩", "tier": 4, "category": "生境", "description": "水把泥泉带出的细泥铺展成周期湿润的平滩。", "art_source": "creation", "art_index": 0},
	"clay_slurry": {"name": "陶浆", "tier": 4, "category": "材料", "description": "黏土加入水后形成便于浇注和细密塑形的浆料。", "art_source": "creation", "art_index": 0},

	"life": {"name": "生命", "tier": 4, "category": "生灵", "description": "湿润生境在持续能量中产生能够自我延续的结构。", "art_source": "material", "art_index": 12},
	"fertile_soil": {"name": "沃土", "tier": 4, "category": "生境", "description": "沼泽沉积物与大地结合形成富含养分的土壤。", "art_source": "material", "art_index": 1},
	"peat": {"name": "泥炭", "tier": 4, "category": "材料", "description": "泥与沼泽残留物在缺氧环境中缓慢压实。", "art_source": "creation", "art_index": 1},
	"reedbed": {"name": "芦苇荡", "tier": 4, "category": "生境", "description": "黏土保持浅水边界，使沼泽植物能够成片扎根。", "art_source": "material", "art_index": 3},
	"thermophile": {"name": "嗜热微生物", "tier": 4, "category": "生灵", "description": "泥泉中的矿物与动力孕育出适应高温的微小生命。", "art_source": "material", "art_index": 12},
	"hot_wetland": {"name": "暖泽", "tier": 4, "category": "生境", "description": "间歇泉持续加热沼泽，形成四季温暖的湿地。", "art_source": "material", "art_index": 12},
	"alpine_wetland": {"name": "山地湿原", "tier": 4, "category": "生境", "description": "山岳阻挡排水，使高处沼泽形成冷凉湿原。", "art_source": "material", "art_index": 3},
	"volcanic_marsh": {"name": "火山湿地", "tier": 4, "category": "生境", "description": "火山云沉降的矿物进入沼泽，形成黑色而肥沃的湿地。", "art_source": "material", "art_index": 12},

	"water_jar": {"name": "水罐", "tier": 4, "category": "生活", "description": "陶器因为盛水而获得储存与运输用途。", "art_source": "creation", "art_index": 3},
	"kiln": {"name": "窑炉", "tier": 4, "category": "工艺", "description": "耐火器壁围住火焰，形成可持续烧制的空间。", "art_source": "creation", "art_index": 7},
	"brick": {"name": "陶砖", "tier": 4, "category": "材料", "description": "黏土经火烧结为规则、坚硬且能够堆砌的构件。", "art_source": "material", "art_index": 1},
	"stone_blade": {"name": "石刃", "tier": 4, "category": "工艺", "description": "山石敲击黑曜石，剥落出可控制的锋利刃缘。", "art_source": "creation", "art_index": 4},
	"mosaic": {"name": "嵌片", "tier": 4, "category": "工艺", "description": "陶器固定细碎黑曜石，形成耐久的装饰表面。", "art_source": "material", "art_index": 11},
	"tile": {"name": "陶瓦", "tier": 4, "category": "材料", "description": "黏土借助陶器模形，获得统一的薄片结构。", "art_source": "material", "art_index": 10},
	"glaze": {"name": "釉", "tier": 4, "category": "材料", "description": "熔岩中的矿物附着陶器并冷却成光滑保护层。", "art_source": "material", "art_index": 9},
	"kettle": {"name": "汽壶", "tier": 4, "category": "生活", "description": "陶器约束蒸汽，让加热、鸣响与出水变得可控。", "art_source": "creation", "art_index": 3},
	"pressure_vessel": {"name": "蓄压罐", "tier": 4, "category": "工艺", "description": "陶器容纳动力并以坚固器壁约束压力。", "art_source": "creation", "art_index": 3},
	"adobe": {"name": "土坯", "tier": 4, "category": "材料", "description": "黏土混入更多土料后能够脱模、晾干并堆砌。", "art_source": "material", "art_index": 1},
	"rammed_earth": {"name": "夯土", "tier": 4, "category": "工艺", "description": "泥与黏土分层压实，形成厚重稳定的墙体。", "art_source": "creation", "art_index": 4},
	"black_mirror": {"name": "玄镜", "tier": 4, "category": "工艺", "description": "黑曜石经火软化并整平，形成深色反光表面。", "art_source": "material", "art_index": 5},
	"obsidian_pebble": {"name": "曜石砾", "tier": 4, "category": "材料", "description": "水流磨去黑曜石尖角，留下圆润而明亮的黑色石砾。", "art_source": "material", "art_index": 5},
	"ceramic_glass": {"name": "熔陶玻璃", "tier": 4, "category": "材料", "description": "熔岩矿物进入黏土并急冷，形成半透明的陶质玻璃。", "art_source": "material", "art_index": 9},
	"ceramic_crust": {"name": "泉烧壳", "tier": 4, "category": "材料", "description": "火烘干泥泉沉积物，留下层叠多孔的矿物硬壳。", "art_source": "creation", "art_index": 7},

	"steam_engine": {"name": "汽动机", "tier": 4, "category": "机械", "description": "蒸汽被动力结构约束并转化为持续机械运动。", "art_source": "creation", "art_index": 4},
	"geothermal_power": {"name": "地热动力", "tier": 4, "category": "原理", "description": "间歇泉的地下热流被整理成能够持续做功的动力。", "art_source": "material", "art_index": 9},
	"hydropower": {"name": "水力", "tier": 4, "category": "原理", "description": "流动水把高差和速度转化为可利用的动力。", "art_source": "material", "art_index": 0},
	"fountain": {"name": "喷泉", "tier": 4, "category": "工程", "description": "陶器管路约束间歇泉，使水柱沿设计好的出口喷出。", "art_source": "creation", "art_index": 3},
	"bathhouse": {"name": "汤屋", "tier": 4, "category": "生活", "description": "蒸汽覆盖泥泉，形成能够保温、沐浴与休息的场所。", "art_source": "creation", "art_index": 7},
	"fumarole": {"name": "喷气孔", "tier": 4, "category": "地貌", "description": "火继续加热间歇泉通道，使水分快速逸散为高温气体。", "art_source": "creation", "art_index": 2},
	"volcanic_soil": {"name": "火山黑土", "tier": 4, "category": "生境", "description": "火山云中的矿物灰与湿泥结合成深色肥沃土层。", "art_source": "material", "art_index": 1}
}

const RECIPES := [
	# 一阶 → 二阶：3 / C(3,2) = 100%
	{"inputs": ["water", "fire"], "output": "steam", "relation": "相变", "logic": "水受热后成为上升的气态水。"},
	{"inputs": ["water", "earth"], "output": "mud", "relation": "混合", "logic": "水进入土，使土变得湿润并可塑。"},
	{"inputs": ["fire", "earth"], "output": "lava", "relation": "相变", "logic": "大地在极热中熔化并流动。"},

	# 累计6个万物后新增11条：ceil(70% × C(6,2)) = 11
	{"inputs": ["water", "steam"], "output": "cloud", "relation": "聚集", "logic": "更多水分让蒸汽聚集成可见云层。"},
	{"inputs": ["water", "mud"], "output": "swamp", "relation": "生境", "logic": "水长期停留在泥地形成湿润沼泽。"},
	{"inputs": ["water", "lava"], "output": "obsidian", "relation": "冷却", "logic": "熔岩急冷形成玻璃质岩石。"},
	{"inputs": ["fire", "steam"], "output": "energy", "relation": "催化", "logic": "持续加热使蒸汽产生压力与做功能力。"},
	{"inputs": ["fire", "mud"], "output": "pottery", "relation": "塑形", "logic": "可塑的泥经烧制固定形状。"},
	{"inputs": ["fire", "lava"], "output": "eruption", "relation": "释放", "logic": "额外热量使熔岩膨胀并突破地表束缚。"},
	{"inputs": ["earth", "steam"], "output": "geyser", "relation": "渗压", "logic": "土层裂隙约束蒸汽，使地下压力周期喷出。"},
	{"inputs": ["earth", "mud"], "output": "clay", "relation": "沉积", "logic": "细土进入泥并均匀沉降，形成致密黏土。"},
	{"inputs": ["earth", "lava"], "output": "mountain", "relation": "地貌", "logic": "熔岩在大地上堆积、凝固并抬升地形。"},
	{"inputs": ["steam", "mud"], "output": "mud_spring", "relation": "渗流", "logic": "蒸汽穿过泥层，把湿泥与矿物带到地表。"},
	{"inputs": ["steam", "lava"], "output": "volcanic_cloud", "relation": "喷发", "logic": "蒸汽接触熔岩后剧烈膨胀并托起火山灰。"},

	# 累计17个万物后新增55条：ceil(40% × C(17,2)) = 55
	{"inputs": ["cloud", "mountain"], "output": "rain", "relation": "降水", "logic": "山岳迫使云层抬升降温，水分凝结落下。"},
	{"inputs": ["cloud", "energy"], "output": "thunderstorm", "relation": "对流", "logic": "云层中的动力累积为强烈对流和雷电。"},
	{"inputs": ["steam", "cloud"], "output": "fog", "relation": "悬浮", "logic": "蒸汽混入低云并在近地面凝成细小水滴。"},
	{"inputs": ["eruption", "cloud"], "output": "pyrocumulus", "relation": "抬升", "logic": "喷发产生的强上升气流把云顶推向高空。"},
	{"inputs": ["volcanic_cloud", "energy"], "output": "volcanic_lightning", "relation": "放电", "logic": "火山云颗粒在剧烈运动中分离电荷并放电。"},
	{"inputs": ["volcanic_cloud", "water"], "output": "ash_rain", "relation": "裹挟", "logic": "水分裹住火山灰并以沉重暗雨落下。"},
	{"inputs": ["earth", "cloud"], "output": "dust_storm", "relation": "卷扬", "logic": "云下气流卷起干土，形成移动的沙尘墙。"},
	{"inputs": ["steam", "volcanic_cloud"], "output": "smog", "relation": "悬浮", "logic": "蒸汽托住细灰，使浑浊气团久久不能沉降。"},
	{"inputs": ["fire", "energy"], "output": "plasma", "relation": "激发", "logic": "火继续注入热量，使动力中的物质进入高能炽亮状态。"},
	{"inputs": ["cloud", "swamp"], "output": "rainforest", "relation": "滋养", "logic": "云层持续补水，让沼泽边缘形成繁盛高湿生境。"},

	{"inputs": ["mountain", "water"], "output": "river", "relation": "侵蚀", "logic": "水沿山势汇集，长期侵蚀出稳定通道。"},
	{"inputs": ["water", "swamp"], "output": "lake", "relation": "汇聚", "logic": "更多水进入低洼沼泽并形成开阔稳定水体。"},
	{"inputs": ["water", "geyser"], "output": "hot_spring", "relation": "蓄积", "logic": "间歇泉得到持续水源，形成长期蓄积的热水池。"},
	{"inputs": ["water", "eruption"], "output": "lahar", "relation": "冲刷", "logic": "水卷走喷发物与松散灰土，形成高速火山泥流。"},
	{"inputs": ["eruption", "mountain"], "output": "volcano", "relation": "堆积", "logic": "反复喷发在山岳上留下稳定火山锥与通道。"},
	{"inputs": ["earth", "eruption"], "output": "crater", "relation": "冲击", "logic": "喷发冲破大地并留下环形凹地。"},
	{"inputs": ["geyser", "mountain"], "output": "geothermal_field", "relation": "聚热", "logic": "山体裂隙汇聚地下热水，形成成片地热区。"},
	{"inputs": ["lava", "swamp"], "output": "new_land", "relation": "冷凝", "logic": "熔岩进入湿地后快速冷却并向水边延伸出新岸。"},
	{"inputs": ["mud", "mountain"], "output": "terrace", "relation": "分层", "logic": "泥被山坡分层拦截，形成连续蓄水台面。"},
	{"inputs": ["clay", "mountain"], "output": "dam", "relation": "封堵", "logic": "黏土封住山谷缺口并形成致密阻水堤体。"},
	{"inputs": ["mud_spring", "mountain"], "output": "mud_valley", "relation": "导流", "logic": "山势约束泥泉流向，长期切出矿泥谷地。"},
	{"inputs": ["earth", "mountain"], "output": "plateau", "relation": "抬升", "logic": "大地继续托举山岳，使大片高处趋于平缓。"},
	{"inputs": ["lava", "mountain"], "output": "volcanic_range", "relation": "侵入", "logic": "熔岩沿山体裂隙反复上涌，形成连续火山带。"},
	{"inputs": ["water", "mud_spring"], "output": "mudflat", "relation": "铺展", "logic": "水把泥泉细泥铺展成周期湿润的平滩。"},
	{"inputs": ["water", "clay"], "output": "clay_slurry", "relation": "调和", "logic": "黏土加入水后形成可浇注的细密陶浆。"},

	{"inputs": ["swamp", "energy"], "output": "life", "relation": "孕育", "logic": "湿润生境在持续能量中产生可自我延续的结构。"},
	{"inputs": ["swamp", "earth"], "output": "fertile_soil", "relation": "沉积", "logic": "沼泽残留物与大地结合，形成富含养分的土壤。"},
	{"inputs": ["mud", "swamp"], "output": "peat", "relation": "压积", "logic": "泥与沼泽残留物在缺氧环境中缓慢压实。"},
	{"inputs": ["swamp", "clay"], "output": "reedbed", "relation": "固岸", "logic": "黏土保持浅水边界，使湿地植物成片扎根。"},
	{"inputs": ["mud_spring", "energy"], "output": "thermophile", "relation": "适应", "logic": "矿物泥泉与持续动力孕育出适应高温的微小生命。"},
	{"inputs": ["swamp", "geyser"], "output": "hot_wetland", "relation": "增温", "logic": "间歇泉持续加热沼泽，形成四季温暖的湿地。"},
	{"inputs": ["swamp", "mountain"], "output": "alpine_wetland", "relation": "滞水", "logic": "山岳阻挡排水，使高处沼泽形成冷凉湿原。"},
	{"inputs": ["swamp", "volcanic_cloud"], "output": "volcanic_marsh", "relation": "富集", "logic": "火山灰中的矿物沉降进入沼泽，形成肥沃黑色湿地。"},

	{"inputs": ["pottery", "water"], "output": "water_jar", "relation": "容纳", "logic": "陶器因为盛水而获得储存与运输用途。"},
	{"inputs": ["pottery", "fire"], "output": "kiln", "relation": "围火", "logic": "耐火器壁围住火焰，形成可持续烧制空间。"},
	{"inputs": ["clay", "fire"], "output": "brick", "relation": "烧结", "logic": "黏土经火烧结为规则坚硬的建筑构件。"},
	{"inputs": ["obsidian", "mountain"], "output": "stone_blade", "relation": "塑形", "logic": "坚硬山石敲击黑曜石，剥落出锋利刃缘。"},
	{"inputs": ["obsidian", "pottery"], "output": "mosaic", "relation": "嵌合", "logic": "陶器固定细碎黑曜石，形成耐久装饰表面。"},
	{"inputs": ["clay", "pottery"], "output": "tile", "relation": "模制", "logic": "黏土借助陶器模形，获得统一薄片结构。"},
	{"inputs": ["lava", "pottery"], "output": "glaze", "relation": "附着", "logic": "熔岩矿物附着陶器并冷却为光滑保护层。"},
	{"inputs": ["steam", "pottery"], "output": "kettle", "relation": "约束", "logic": "陶器约束蒸汽，让加热、鸣响与出水变得可控。"},
	{"inputs": ["energy", "pottery"], "output": "pressure_vessel", "relation": "蓄压", "logic": "陶器以坚固器壁容纳并约束动力压力。"},
	{"inputs": ["earth", "clay"], "output": "adobe", "relation": "配土", "logic": "黏土混入土料后能够脱模、晾干并堆砌。"},
	{"inputs": ["mud", "clay"], "output": "rammed_earth", "relation": "压实", "logic": "泥与黏土分层压实，形成厚重稳定墙体。"},
	{"inputs": ["fire", "obsidian"], "output": "black_mirror", "relation": "整平", "logic": "黑曜石经火软化并整平，形成深色反光表面。"},
	{"inputs": ["water", "obsidian"], "output": "obsidian_pebble", "relation": "磨蚀", "logic": "水流磨去黑曜石尖角，留下圆润明亮石砾。"},
	{"inputs": ["lava", "clay"], "output": "ceramic_glass", "relation": "熔合", "logic": "熔岩矿物进入黏土并急冷，形成半透明陶质玻璃。"},
	{"inputs": ["fire", "mud_spring"], "output": "ceramic_crust", "relation": "烘结", "logic": "火烘干泥泉沉积物，留下层叠多孔的矿物硬壳。"},

	{"inputs": ["steam", "energy"], "output": "steam_engine", "relation": "做功", "logic": "蒸汽被动力结构约束并转化为持续机械运动。"},
	{"inputs": ["geyser", "energy"], "output": "geothermal_power", "relation": "转化", "logic": "间歇泉的地下热流被整理成可持续做功的动力。"},
	{"inputs": ["water", "energy"], "output": "hydropower", "relation": "转化", "logic": "流动水把高差和速度转化为可利用的动力。"},
	{"inputs": ["geyser", "pottery"], "output": "fountain", "relation": "导流", "logic": "陶器管路约束间歇泉，使水柱沿固定出口喷出。"},
	{"inputs": ["steam", "mud_spring"], "output": "bathhouse", "relation": "保温", "logic": "蒸汽覆盖泥泉，形成能够沐浴与休息的温热场所。"},
	{"inputs": ["fire", "geyser"], "output": "fumarole", "relation": "蒸干", "logic": "火继续加热泉道，使水分快速逸散为高温气体。"},
	{"inputs": ["mud", "volcanic_cloud"], "output": "volcanic_soil", "relation": "富集", "logic": "火山灰中的矿物与湿泥结合成深色肥沃土层。"}
]
